# Generated by Django 3.1.6 on 2021-02-06 18:50

import appmain.utils.paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to=appmain.utils.paths.upload_photo_user)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appmain.person')),
            ],
            bases=('appmain.person',),
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appmain.person')),
                ('town_hall_number', models.PositiveIntegerField()),
            ],
            bases=('appmain.person',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=appmain.utils.paths.upload_photo_user)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.salesman')),
            ],
        ),
    ]
